### ISSUE TITLE
git node land doesn't finalize with single commit

### ISSUE THREAD

**Issue by devsnek** [nodejs/node-core-utils#173] opened 2018-02-10 03:25 UTC
according to qiuyi when the landing only has a single commit running `--final` shouldn't be needed but twice so far i've observed needing to explicitly run it.

both times were with simple single-commit prs, just ran `git commit land $ID` and hit `y` a bunch of times, then `git push upstream master`

**Comment by joyeecheung** [comment] 2018-07-04 23:48
@devsnek Have you seen the issue again? Where did `git-node` stop when you encounter the issue, did it stop after validating the final commit? Without a repro it won't be very actionable at this point.

**Comment by devsnek** [comment] 2018-07-04 23:59
@joyeecheung I'll let you know after I land another pr

**Comment by devsnek** [comment] 2018-07-05 21:53
@joyeecheung 

![](https://gc.gy/礪.png)

and 

```bash
$ ls .ncu/21518/
8f024f3-message  6827ce8-message  metadata  patch
```

**Comment by devsnek** [comment] 2018-07-05 22:00
landing 21644 had a last option `? Clean up generated temporary files? [Y/n]` which seems to have done what it was supposed to, i didn't need to run --final with it

**Comment by joyeecheung** [comment] 2018-07-06 01:54
@devsnek I am not sure what the issue is...have you landed 21518 without cleaning up the temporary files?

**Comment by devsnek** [comment] 2018-07-06 01:57
@joyeecheung it was just the last pr i landed, and it didn't clean up, but 21644 cleaned up so i assume this is fixed now

**Comment by joyeecheung** [comment] 2018-07-06 06:38
@devsnek Good to know, I'll close this one for now. If you see this happen again please reopen or open a new issue, thanks

**Closed by joyeecheung** 2018-07-06 06:38 UTC
Labels: git-node
