### ISSUE TITLE
Recognise links to node-test-commit-lite

### ISSUE THREAD

**Issue by gibfahn** [nodejs/node-core-utils#214] opened 2018-03-09 17:22 UTC
I tend to leave links to [node-test-commit](https://ci.nodejs.org/job/node-test-commit/) and [node-test-commit-lite](https://ci.nodejs.org/job/node-test-commit-lite/) rather than the `pull-request` equivalents, because that way it's one less click to get to the sub-job list.

However it seems that `git node land` doesn't pick up the URL:

```console
$ git node land 19164
✔  Done loading data for nodejs/node/pull/19164
----------------------------------- PR info ------------------------------------
Title      build: update arm minimum supported platform (#19164)
Author     Gibson Fahnestock <gib@uk.ibm.com> (@gibfahn)
Branch     gibfahn:arm-libc -> nodejs:master
Labels     build, doc, lts-watch-v4.x, lts-watch-v6.x, lts-watch-v8.x
Commits    2
 - build: update arm minimum supported platform
 - squash: only change arm64
Committers 1
 - Gibson Fahnestock <gibfahn@gmail.com>
------------------------------ Generated metadata ------------------------------
PR-URL: https://github.com/nodejs/node/pull/19164
Fixes: https://github.com/nodejs/build/issues/1164
Reviewed-By: Rod Vagg <rod@vagg.org>
Reviewed-By: Michael Dawson <michael_dawson@ca.ibm.com>
--------------------------------------------------------------------------------
✔  Requested Changes: 0
✔  Approvals: 2, 2 from TSC (rvagg, mhdawson)
✖  No CI runs detected
--------------------------------------------------------------------------------
? This PR is not ready to land, do you want to continue? [Y/n]
```

![image](https://user-images.githubusercontent.com/15943089/37220312-255cfaa8-23be-11e8-91bc-ac441dd57f99.png)

Note that I just renamed the `node-test-commit-lite` job, but from a quick glance at the source code that shouldn't make a difference.

https://github.com/nodejs/node-core-utils/blob/2c350ddf55d997b2e812763f88d96a89329f665a/lib/ci.js#L16-L26

**Comment by richardlau** [comment] 2018-03-09 17:44
@gibfahn https://github.com/nodejs/node-core-utils/pull/171

**Comment by richardlau** [comment] 2018-03-09 17:49
Also this is a duplicate of https://github.com/nodejs/node-core-utils/issues/170

**Comment by cPhost** [comment] 2018-03-09 17:49
This is a duplicate of #170, closing this in favor of #170.

**Closed** 2018-03-09 17:50 UTC

**Comment by cPhost** [comment] 2018-03-09 17:51
@richardlau got me by seconds 😀.
