### ISSUE TITLE
Sync error not helpful

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/node-core-utils#439] opened 2020-06-08 19:27 UTC
I just wanted to backport a PR and I got the following error:

```console
$ git node backport 33490 --to 14
Error
    at exports.runSync (/home/ruben/.nvm/versions/node/v14.2.0/lib/node_modules/node-core-utils/lib/run.js:60:11)
    at new Session (/home/ruben/.nvm/versions/node/v14.2.0/lib/node_modules/node-core-utils/lib/session.js:28:26)
    at new BackportSession (/home/ruben/.nvm/versions/node/v14.2.0/lib/node_modules/node-core-utils/lib/backport_session.js:18:5)
    at main (/home/ruben/.nvm/versions/node/v14.2.0/lib/node_modules/node-core-utils/components/git/backport.js:48:19)
    at Object.handler (/home/ruben/.nvm/versions/node/v14.2.0/lib/node_modules/node-core-utils/components/git/backport.js:66:21)
    at Object.runCommand (/home/ruben/.nvm/versions/node/v14.2.0/lib/node_modules/node-core-utils/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/home/ruben/.nvm/versions/node/v14.2.0/lib/node_modules/node-core-utils/node_modules/yargs/yargs.js:1154:41)
    at Object.get [as argv] (/home/ruben/.nvm/versions/node/v14.2.0/lib/node_modules/node-core-utils/node_modules/yargs/yargs.js:1088:21)
    at Object.<anonymous> (/home/ruben/.nvm/versions/node/v14.2.0/lib/node_modules/node-core-utils/bin/git-node:20:3)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
```

We should probably include `stdout` as well and maybe there's more to improve the error somewhere else as well.

**Comment by codebytere** [comment] 2020-06-08 19:43
@BridgeAR this was fixed in https://github.com/nodejs/node-core-utils/pull/426 - it just hasn't been published yet :)

**Comment by BridgeAR** [comment] 2020-06-08 19:48
Awesome! Should we maybe also include a hint how to fix that?

**Comment by gengjiawen** [comment] 2020-06-22 11:28
Can new release on schedule ? running into same issue.

**Comment by gengjiawen** [comment] 2020-06-22 11:40
With master looks like still exists:

```console
root@localhost ~/node (master)# git node land 33975
Error
    at exports.runSync (/usr/local/lib/node_modules/node-core-utils/lib/run.js:60:11)
    at new Session (/usr/local/lib/node_modules/node-core-utils/lib/session.js:32:26)
    at new LandingSession (/usr/local/lib/node_modules/node-core-utils/lib/landing_session.js:19:5)
    at main (/usr/local/lib/node_modules/node-core-utils/components/git/land.js:131:17)
    at land (/usr/local/lib/node_modules/node-core-utils/components/git/land.js:114:21)
    at Object.handler (/usr/local/lib/node_modules/node-core-utils/components/git/land.js:78:14)
    at Object.runCommand (/usr/local/lib/node_modules/node-core-utils/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/node-core-utils/node_modules/yargs/yargs.js:1154:41)
    at Object.get [as argv] (/usr/local/lib/node_modules/node-core-utils/node_modules/yargs/yargs.js:1088:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-core-utils/bin/git-node:20:3)
```

**Comment by gengjiawen** [comment] 2020-06-22 12:14
My root cause is I misconfig upstream. The raw git command `git config --get` just return 1 with no stderr and stdout.

**Comment by codebytere** [comment] 2020-06-30 14:46
Closing as resolved by https://github.com/nodejs/node-core-utils/pull/426

**Closed by codebytere** 2020-06-30 14:46 UTC
