### ISSUE TITLE
bash script to land a PR?

### ISSUE THREAD

**Issue by mcollina** [nodejs/node-core-utils#95] opened 2017-11-08 11:22 UTC
I wrote this:

```sh
#! /bin/bash

set -x
set -e

curl -L https://github.com/nodejs/node/pull/$1.patch | git am --whitespace=fix
get-metadata $1 -f msg.txt
echo -e "$(git show -s --format=%B)\n\n$(cat msg.txt)" > msg.txt
git commit --amend -F msg.txt
git show -s --format=%B
./configure
make -j4 test
```

I think it might be something we might want to add here, in node, or mention it in the README

**Comment by joyeecheung** [comment] 2017-11-08 11:43
@mcollina I have a few custom git commands that are in essense using the same commands as the OP + some additional checking and configuration, I plan to open a PR later this week to see what people thinks. (If we point them to `git-*` bin targets of `package.json`, those will automatically appear as git commands).

Here is a preview. I plan to make another one that handles the single-commit case so there will only be one command needed for the simplest cases.

<img width="740" alt="screen shot 2017-11-08 at 4 47 45 pm" src="https://user-images.githubusercontent.com/4299420/32547315-8050454a-c447-11e7-8232-dd70d72933dd.png">

**Comment by Tiriel** [comment] 2017-11-10 11:07
Ref: #98

**Comment by BridgeAR** [comment] 2017-12-12 13:17
As I also use a very similar bash script at the moment - to handle multiple commits at a time I also added a conditional rebase

```bash
COMMITS=$(git rev-list --count master...upstream/master)
if [ $COMMITS != "1" ]
then
  git rebase -i origin/master
fi
```

**Comment by BridgeAR** [comment] 2017-12-12 15:57
I actually played a bit around and my script and it got a bit more sophisticated. Note - I use `xclip` to copy the message into the clipboard. 
```bash
#!/bin/bash

set -x
set -e

if [ $1 != "verify" ]
then

  # Get the patch
  curl -L https://github.com/nodejs/node/pull/$1.patch | git am --whitespace=fix

  # Get metadata and add it to the commit message
  METADATA=$(get-metadata $1 -f)
  NEW_MESSAGE="$(git show -s --format=%B)\n\n$METADATA"

  # Check for more than one commit
  COMMITS=$(git rev-list --count master...origin/master)
  if [ $COMMITS != "1" ]
  then
    # Copy the part to add to the clipboard and call rebase
    echo $METADATA | xclip -sel clip
    git rebase -i origin/master
  fi

  # Run linter
  make lint

  # Update commits left
  COMMITS=$(git rev-list --count master...origin/master)

  # If there is one commit left add the commit message, else we already did that while rebasing
  if [ $COMMITS = "1" ]
  then
    NEW_MESSAGE="$(git show -s --format=%B)\n\n$METADATA"
    git commit --amend -m $NEW_MESSAGE
  fi

else
  COMMITS=$(git rev-list --count master...origin/master)
fi

# Validate all commit messages
VALIDATE=$(git rev-list master...origin/master | xargs core-validate-commit)

# Print the message for the PR
COMMIT_IDS=$(git log --format="%H" -n $COMMITS)
echo "Landed in ${COMMIT_IDS//$'\n'/, }"

# TODO
# Comment and close automatically with a github command?
# Push...
```

**Comment by cPhost** [comment] 2017-12-12 16:18
Hey @BridgeAR `xclip` for copying data is a great idea but the problem is bash pr is till Work in Progress.

**Comment by BridgeAR** [comment] 2017-12-12 18:04
@cPhost I just thought I might share it as it does a few more things and if someone wants to use, they can. I am probably going to improve that a bit further from time to time.

**Comment by BridgeAR** [comment] 2018-01-12 17:25
The current version of my script does quite a lot automated already. It will e.g. rebase nicely and stuff like that. In the end it copies a message for the users in the clipboard in a nice way as well.

**Comment by BridgeAR** [comment] 2018-01-12 17:25
Note: I have a "weird" setup so most people would have to switch `origin/master` to `upstream/master`.

**Comment by joyeecheung** [comment] 2018-01-17 19:17
I guess this is fixed now that `git-node-land` has landed.

**Closed by joyeecheung** 2018-01-17 19:17 UTC
Labels: Work In Progress
